/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['middleware/index.js']) {
  _$jscoverage['middleware/index.js'] = [];
  _$jscoverage['middleware/index.js'][1] = 0;
}
_$jscoverage['middleware/index.js'][1]++;
module.exports = {JSONTransport: require("json-transport"), httpAuth: require("./httpauth"), payloadParser: require("./payload-parser"), multipartParser: require("./multipart-parser")};
_$jscoverage['middleware/index.js'].source = ["module.exports = {","  JSONTransport: require('json-transport'),","  httpAuth: require('./httpauth'),","  payloadParser: require('./payload-parser'),","  multipartParser: require('./multipart-parser')","}"];
