/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['middleware/multipart-parser.js']) {
  _$jscoverage['middleware/multipart-parser.js'] = [];
  _$jscoverage['middleware/multipart-parser.js'][1] = 0;
  _$jscoverage['middleware/multipart-parser.js'][3] = 0;
  _$jscoverage['middleware/multipart-parser.js'][4] = 0;
  _$jscoverage['middleware/multipart-parser.js'][5] = 0;
  _$jscoverage['middleware/multipart-parser.js'][6] = 0;
  _$jscoverage['middleware/multipart-parser.js'][8] = 0;
  _$jscoverage['middleware/multipart-parser.js'][9] = 0;
  _$jscoverage['middleware/multipart-parser.js'][10] = 0;
  _$jscoverage['middleware/multipart-parser.js'][11] = 0;
  _$jscoverage['middleware/multipart-parser.js'][12] = 0;
  _$jscoverage['middleware/multipart-parser.js'][14] = 0;
}
_$jscoverage['middleware/multipart-parser.js'][1]++;
var formidable = require("formidable");
_$jscoverage['middleware/multipart-parser.js'][3]++;
module.exports = (function () {
  _$jscoverage['middleware/multipart-parser.js'][4]++;
  return (function (request, response, next) {
  _$jscoverage['middleware/multipart-parser.js'][5]++;
  if (! request.method.match(/(PUT|POST|OPTIONS)/)) {
    _$jscoverage['middleware/multipart-parser.js'][6]++;
    return next();
  }
  _$jscoverage['middleware/multipart-parser.js'][8]++;
  if (request.headers["content-type"].match(/multipart\/form-data/)) {
    _$jscoverage['middleware/multipart-parser.js'][9]++;
    request.resume();
    _$jscoverage['middleware/multipart-parser.js'][10]++;
    request.form = new formidable.IncomingForm();
    _$jscoverage['middleware/multipart-parser.js'][11]++;
    request.form.parse(request);
    _$jscoverage['middleware/multipart-parser.js'][12]++;
    return next();
  }
  _$jscoverage['middleware/multipart-parser.js'][14]++;
  next();
});
});
_$jscoverage['middleware/multipart-parser.js'].source = ["var formidable = require('formidable')","","module.exports = function () {","  return function (request, response, next) {","    if (!request.method.match(/(PUT|POST|OPTIONS)/)) {","      return next()","    }","    if (request.headers['content-type'].match(/multipart\\/form-data/)) {","      request.resume()","      request.form = new formidable.IncomingForm()","      request.form.parse(request)","      return next()","    }","    next()","  }","}"];
