/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['middleware/payload-parser.js']) {
  _$jscoverage['middleware/payload-parser.js'] = [];
  _$jscoverage['middleware/payload-parser.js'][1] = 0;
  _$jscoverage['middleware/payload-parser.js'][4] = 0;
  _$jscoverage['middleware/payload-parser.js'][5] = 0;
  _$jscoverage['middleware/payload-parser.js'][6] = 0;
  _$jscoverage['middleware/payload-parser.js'][7] = 0;
  _$jscoverage['middleware/payload-parser.js'][9] = 0;
  _$jscoverage['middleware/payload-parser.js'][10] = 0;
  _$jscoverage['middleware/payload-parser.js'][11] = 0;
  _$jscoverage['middleware/payload-parser.js'][13] = 0;
  _$jscoverage['middleware/payload-parser.js'][14] = 0;
  _$jscoverage['middleware/payload-parser.js'][15] = 0;
  _$jscoverage['middleware/payload-parser.js'][16] = 0;
  _$jscoverage['middleware/payload-parser.js'][17] = 0;
  _$jscoverage['middleware/payload-parser.js'][18] = 0;
  _$jscoverage['middleware/payload-parser.js'][19] = 0;
  _$jscoverage['middleware/payload-parser.js'][21] = 0;
  _$jscoverage['middleware/payload-parser.js'][22] = 0;
  _$jscoverage['middleware/payload-parser.js'][26] = 0;
}
_$jscoverage['middleware/payload-parser.js'][1]++;
var querystring = require("querystring"), BufferJoiner = require("bufferjoiner");
_$jscoverage['middleware/payload-parser.js'][4]++;
module.exports = (function () {
  _$jscoverage['middleware/payload-parser.js'][5]++;
  return (function (request, response, next) {
  _$jscoverage['middleware/payload-parser.js'][6]++;
  if (! request.method.match(/(PUT|POST|OPTIONS)/)) {
    _$jscoverage['middleware/payload-parser.js'][7]++;
    return next();
  }
  _$jscoverage['middleware/payload-parser.js'][9]++;
  request.rawBody = new BufferJoiner();
  _$jscoverage['middleware/payload-parser.js'][10]++;
  request.on("data", (function (chunk) {
  _$jscoverage['middleware/payload-parser.js'][11]++;
  request.rawBody.add(chunk);
}));
  _$jscoverage['middleware/payload-parser.js'][13]++;
  request.once("end", (function () {
  _$jscoverage['middleware/payload-parser.js'][14]++;
  request.rawBody = request.rawBody.join();
  _$jscoverage['middleware/payload-parser.js'][15]++;
  if (request.headers["content-type"].match(/application\/x-www-form-urlencoded/)) {
    _$jscoverage['middleware/payload-parser.js'][16]++;
    request.body = querystring.parse(request.rawBody.toString("utf8"));
  }
  else {
    _$jscoverage['middleware/payload-parser.js'][17]++;
    if (request.headers["content-type"].match(/application\/json/)) {
      _$jscoverage['middleware/payload-parser.js'][18]++;
      try {
        _$jscoverage['middleware/payload-parser.js'][19]++;
        request.body = JSON.parse(request.rawBody.toString("utf8"));
      }
      catch (e) {
        _$jscoverage['middleware/payload-parser.js'][21]++;
        request.parseError = e;
        _$jscoverage['middleware/payload-parser.js'][22]++;
        request.body = Object.create(null);
      }
    }
  }
}));
  _$jscoverage['middleware/payload-parser.js'][26]++;
  next();
});
});
_$jscoverage['middleware/payload-parser.js'].source = ["var querystring = require('querystring'),","    BufferJoiner = require('bufferjoiner')","","module.exports = function () {","  return function (request, response, next) {","    if (!request.method.match(/(PUT|POST|OPTIONS)/)) {","      return next()","    }","    request.rawBody = new BufferJoiner()","    request.on('data', function (chunk) {","      request.rawBody.add(chunk)","    })","    request.once('end', function () {","      request.rawBody = request.rawBody.join()","      if (request.headers['content-type'].match(/application\\/x-www-form-urlencoded/)) {","        request.body = querystring.parse(request.rawBody.toString('utf8'))","      } else if (request.headers['content-type'].match(/application\\/json/)) {","        try {","          request.body = JSON.parse(request.rawBody.toString('utf8'))","        } catch(e) {","          request.parseError = e","          request.body = Object.create(null)","        }","      }","    })","    next()","  }","}"];
